// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Parms struct {
	Name string `json:"name"`
	Role int    `json:"role"`
}

type TeacherInfo struct {
	ID           int             `json:"id"`
	Name         string          `json:"name"`
	Avatar       string          `json:"avatar"`
	Info         string          `json:"info"`
	Score        float64         `json:"score"`
	Role         int             `json:"role"`
	TeacherScore []*TeacherScore `json:"teacherScore" gorm:"foreignkey:TID"`
}

type TeacherScore struct {
	ID      int     `json:"id"`
	TID     int     `json:"t_id"`
	Comment string  `json:"comment"`
	UID     int     `json:"u_id"`
	Score   float64 `json:"score"`
}

type InsertInfo struct {
	Name   string  `json:"name"`
	Avatar *string `json:"avatar"`
	Info   string  `json:"info"`
}

type UpdateInfo struct {
	ID     int    `json:"id"`
	Name   string `json:"name"`
	Avatar string `json:"avatar"`
	Info   string `json:"info"`
}
